# Generated by Django 2.0.1 on 2018-01-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('height', models.IntegerField(max_length=5)),
                ('weight', models.IntegerField(max_length=5)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
